# Generated by Django 5.0.7 on 2024-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osn', '0002_book_author_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
