# Generated by Django 5.0.7 on 2024-07-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osn', '0003_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50)),
                ('when', models.CharField(max_length=50)),
                ('kom', models.TextField(max_length=2000)),
            ],
        ),
    ]
